name: CI for main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install electron project dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Compile TypeScript
      run: npx tsc

    - name: Make application distributables with electron-forge
      run: npx electron-forge make

    - name: Run Playwright tests
      run: npx playwright test
